name: Tests

on:
  push:
    branches: [v10-lts]
  pull_request:
    branches: [v10-lts]

jobs:
  test:
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        ruby: ['1.9.3', '2.2', '2.5.9', '2.7.5']

    steps:
      - uses: actions/checkout@v2
      - name: Install ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
      - name: Bundle
        run: 'bundle install --no-deployment'
      - name: Run tests
        run: 'bundle exec rake test'
